runtime: python27
api_version: '1'
env: standard
threadsafe: true
default_expiration: 31536000s
handlers:
  - url: /
    secure: always
    application_readable: false
    http_headers:
      Referrer-Policy: unsafe-url
      Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
      Vary: Accept-Encoding
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      X-Xss-Protection: 1; mode=block
    static_files: www/index.html
    require_matching_file: false
    upload: www/index.html
  - url: '/(.*)'
    secure: always
    application_readable: false
    http_headers:
      Referrer-Policy: unsafe-url
      Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
      Vary: Accept-Encoding
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      X-Xss-Protection: 1; mode=block
    static_files: "www/\\1"
    require_matching_file: false
    upload: 'www/(.*)'
  - url: "/(.*\\.(ico|png))$"
    secure: always
    application_readable: false
    http_headers:
      Referrer-Policy: unsafe-url
      Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
      Vary: Accept-Encoding
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      X-Xss-Protection: 1; mode=block
    static_files: "www/\\1"
    require_matching_file: false
    upload: "www/.*\\.(ico|png)$"
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic