runtime: python27
env: standard
threadsafe: true
default_expiration: "365d"
handlers:
  - url: /.well-known
    static_dir: well-known
    secure: always
  - url: /
    static_files: www/index.html
    upload: www/index.html
    secure: always
  - url: '/(.*)'
    static_files: "www/\\1"
    upload: 'www/(.*)'
    secure: always
  - url: "/(.*\\.(ico|png))$"
    static_files: www/\1
    upload: www/.*\.(ico|png)$
    secure: always
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
error_handlers:
  - file: www/404.html
