runtime: python27
env: standard
threadsafe: true
default_expiration: 31536000s
handlers:
  - url: '/.well-known/(.*)'
    secure: always
    application_readable: false
    static_files: "well-known/\\1"
    require_matching_file: false
    upload: 'well-known/.*'
  - url: /
    secure: always
    application_readable: true
    static_files: __static__/www/index.html
    require_matching_file: true
    upload: __static__/www/index.html
  - url: '/(.*)'
    secure: always
    application_readable: true
    static_files: "__static__/www/\\1"
    require_matching_file: true
    upload: '__static__/www/(.*)'
  - url: "/(.*\\.(ico|png))$"
    secure: always
    application_readable: true
    static_files: "__static__/__static__/www/\\1"
    require_matching_file: true
    upload: "__static__/__static__/www/.*\\.(ico|png)$"
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
