runtime: python27
api_version: 1
default_expiration: "365d"
threadsafe: true

handlers:
- url: /.well-known
  static_dir: .well-known
  static_files: www/.well-known/acme-challenge/index.html

- url: /
  static_files: www/index.html
  upload: www/index.html
  
- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

- url: /(.*\.(ico|png))$
  static_files: www/\1
  upload: www/.*\.(ico|png)$
  application_readable: true

error_handlers:
- file: www/404.html
